categories:
- Astronomy
description: CRbeam
homepage_url: null
long_description: CRbeam
name: CRbeam
owner: astroteam
remote_repository_url: https://github.com/esg-epfl-apc/tools-astro/tree/main/tools
type: unrestricted
