name: update-archives-list
run-name: Updating archives list
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  run-archive-script:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install pyvo and required dependencies
        run: | 
          python -m ensurepip --upgrade
          pip install astropy
          pip install requests
          pip install pyvo

      - name: run archives script
        run: python fetch_archives.py

      - name: List files after script execution
        run: ls -la

      - name: create pull request
        run: gh pr create -B main -H archives-tool-githubaction-archives-list-update --title 'Archives list update' --body 'Automated pull request for archives list update'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
